"""Add user-intersection relationship

Revision ID: 251ec09757bf
Revises: 962dcb8e2f1c
Create Date: 2025-01-22 13:55:07.357705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '251ec09757bf'
down_revision = '962dcb8e2f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_intersection',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'intersection_id')
    )
    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_phases', sa.Integer(), nullable=False))
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('canton',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('coordinates',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=mysql.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('coordinates',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('canton',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('province',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('num_phases')

    op.drop_table('user_intersection')
    # ### end Alembic commands ###
