"""Add Phase, Flow, and LaneFlow models

Revision ID: 2b5778bb679a
Revises: f935b1b31f70
Create Date: 2025-01-27 11:39:07.170840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5778bb679a'
down_revision = 'f935b1b31f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_number', sa.Integer(), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lane_flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lane_parameter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lane_flow')
    op.drop_table('flow')
    op.drop_table('phase')
    # ### end Alembic commands ###
