"""Updated AdaptiveControlConfig model

Revision ID: 3816bb542564
Revises: f8b1aef8f7fc
Create Date: 2025-01-29 14:04:18.411038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3816bb542564'
down_revision = 'f8b1aef8f7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adaptive_control_config', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['controller_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adaptive_control_config', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
