"""Add TrafficController model

Revision ID: 44f1f5ea231b
Revises: 251ec09757bf
Create Date: 2025-01-22 14:52:18.440545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44f1f5ea231b'
down_revision = '251ec09757bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traffic_controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_name', sa.String(length=100), nullable=False),
    sa.Column('controller_id', sa.String(length=50), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.Column('adaptive_plan', sa.String(length=20), nullable=False),
    sa.Column('green_1', sa.String(length=20), nullable=False),
    sa.Column('green_2', sa.String(length=20), nullable=False),
    sa.Column('green_3', sa.String(length=20), nullable=False),
    sa.Column('green_4', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traffic_controller')
    # ### end Alembic commands ###
