"""Add models new phases and flows

Revision ID: 453a21ffc6b8
Revises: fd12e890c309
Create Date: 2025-01-27 22:07:44.469533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453a21ffc6b8'
down_revision = 'fd12e890c309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('phase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flow_lane',
    sa.Column('flow_id', sa.Integer(), nullable=False),
    sa.Column('lane_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['lane_id'], ['lane_parameter.id'], ),
    sa.PrimaryKeyConstraint('flow_id', 'lane_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flow_lane')
    op.drop_table('flow')
    op.drop_table('phase')
    # ### end Alembic commands ###
