"""Added AdaptiveResults model

Revision ID: 5c2b42521ba2
Revises: 3816bb542564
Create Date: 2025-01-30 11:04:43.624503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2b42521ba2'
down_revision = '3816bb542564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptive_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('flow', sa.Integer(), nullable=False),
    sa.Column('sample_time', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('num_vehicles', sa.Integer(), nullable=False),
    sa.Column('num_lanes', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adaptive_results')
    # ### end Alembic commands ###
