"""Updated TrafficController model

Revision ID: 645cee383218
Revises: 44f1f5ea231b
Create Date: 2025-01-24 14:16:56.433002

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '645cee383218'
down_revision = '44f1f5ea231b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_controller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('identifier', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['identifier'])
        batch_op.drop_column('controller_name')
        batch_op.drop_column('green_4')
        batch_op.drop_column('green_1')
        batch_op.drop_column('adaptive_plan')
        batch_op.drop_column('green_3')
        batch_op.drop_column('controller_id')
        batch_op.drop_column('green_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_controller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('green_2', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('controller_id', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('green_3', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('adaptive_plan', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('green_1', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('green_4', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('controller_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('identifier')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
