"""Added relationship between AdaptiveResults and TrafficController

Revision ID: 67d99ec6ce77
Revises: 5c2b42521ba2
Create Date: 2025-01-30 11:11:26.199714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d99ec6ce77'
down_revision = '5c2b42521ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adaptive_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('controller_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'traffic_controller', ['controller_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adaptive_results', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('controller_id')

    # ### end Alembic commands ###
