"""Add Lane model

Revision ID: 742df871da8c
Revises: 2b5778bb679a
Create Date: 2025-01-27 14:09:01.784908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742df871da8c'
down_revision = '2b5778bb679a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane_number', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.Integer(), nullable=False),
    sa.Column('intersection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], ),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lane')
    # ### end Alembic commands ###
