"""nueva funcionalidad

Revision ID: c0a5700f604d
Revises: 453a21ffc6b8
Create Date: 2025-01-29 11:14:52.103381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a5700f604d'
down_revision = '453a21ffc6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lane_parameter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'flow', ['flow_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lane_parameter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flow_id')

    # ### end Alembic commands ###
