"""Added PhaseTimingResults model

Revision ID: cc0725fd0f8f
Revises: 67d99ec6ce77
Create Date: 2025-01-31 12:56:11.677486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0725fd0f8f'
down_revision = '67d99ec6ce77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase_timing_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('calculated_time', sa.Integer(), nullable=False),
    sa.Column('suggested_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['traffic_controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_timing_results')
    # ### end Alembic commands ###
