"""Add cloud_id to Intersection model

Revision ID: d313ad0fd2dc
Revises: 73f0d1f01c04
Create Date: 2025-01-08 15:13:55.402939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd313ad0fd2dc'
down_revision = '73f0d1f01c04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cloud_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('intersection', schema=None) as batch_op:
        batch_op.drop_column('cloud_id')

    # ### end Alembic commands ###
