"""Added Adaptive Control Configuration model

Revision ID: f8b1aef8f7fc
Revises: c0a5700f604d
Create Date: 2025-01-29 13:45:00.954091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b1aef8f7fc'
down_revision = 'c0a5700f604d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adaptive_control_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('controller_id', sa.Integer(), nullable=False),
    sa.Column('saturation_flow', sa.Integer(), nullable=False),
    sa.Column('amber_time', sa.Integer(), nullable=False),
    sa.Column('clearance_time', sa.Integer(), nullable=False),
    sa.Column('green_time_1', sa.Integer(), nullable=False),
    sa.Column('green_time_2', sa.Integer(), nullable=False),
    sa.Column('green_time_3', sa.Integer(), nullable=False),
    sa.Column('green_time_4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['traffic_controller.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adaptive_control_config')
    # ### end Alembic commands ###
