"""regreso

Revision ID: fd12e890c309
Revises: 742df871da8c
Create Date: 2025-01-27 14:18:36.711448

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd12e890c309'
down_revision = '742df871da8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lane')
    op.drop_table('lane_flow')
    op.drop_table('flow')
    op.drop_table('phase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phase',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phase_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intersection_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], name='phase_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('flow',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flow_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phase_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase.id'], name='flow_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lane_flow',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('flow_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lane_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], name='lane_flow_ibfk_1'),
    sa.ForeignKeyConstraint(['lane_id'], ['lane_parameter.id'], name='lane_flow_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('lane',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lane_number', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('camera_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('intersection_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['camera.id'], name='lane_ibfk_1'),
    sa.ForeignKeyConstraint(['intersection_id'], ['intersection.id'], name='lane_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
